### ISSUE TITLE
clearing the scene of existing meshes

### ISSUE THREAD

**Issue by adamredwoods** [shawn0326/zen-3d#1]
I really enjoy how light weight this library is, but I cannot find a way to clear the scene. If I apply a new scene to the renderer, the old objects are not removed. I have also tried removing objects from a group container, but after the old objects are removed, new ones do not show up.

Could be a bug or could be doing something wrong. Any suggestions?

**Comment by shawn0326** [comment]
@adamredwoods 

In general, you can use scene.remove() to remove an Object3D from scene.

Can you show me your code?
