### ISSUE TITLE
So hard to make it working with this post processing?

### ISSUE THREAD

**Issue by VanderSP** [shawn0326/zen-3d#21]
Hi Shawn... it would be hard to make zen3d compatible with: [https://github.com/vanruesc/postprocessing](https://github.com/vanruesc/postprocessing) ?

**Comment by shawn0326** [comment]
I'm afraid you need to rewrite some shaders and follow the rules of zen3d

**Comment by VanderSP** [comment]
Oh I see... anyway that godrays looks really cool!

**Comment by VanderSP** [comment]
what i really like the most in this lib, is the performance of animating shaders like the sky.... threejs is totally slow on this!
